services:
  scanner:
    image: ghcr.io/guthriekenosha/smart_scanner:latest

  dashboard:
    image: ghcr.io/guthriekenosha/smart-scanner-webdash:latest
    container_name: perp-dashboard
    restart: unless-stopped
    environment:
      - METRICS_PATH=/data/scanner_metrics.jsonl
    volumes:
      - perpdata:/data:ro
    ports:
      - "8081:8081"
